version: '3.8'

services:
  app:
    container_name: deokhugam-app
    build:
      context: .
      dockerfile: Dockerfile
    image: deokhugam:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deokhugam
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      STORAGE_TYPE: s3
      STORAGE_LOCAL_ROOT_PATH: /app/.deokhugam/storage
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: 600
    depends_on:
      - db
    volumes:
      - binary-content-storage:/app/.deokhugam/storage
    networks:
      - deokhugam-network

  db:
    image: postgres:16-alpine
    container_name: deokhugam-db
    environment:
      POSTGRES_DB: deokhugam
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - deokhugam-network

volumes:
  postgres-data:
  binary-content-storage:

networks:
  deokhugam-network:
    driver: bridge
